app:
  name: home-manager
  repository: rummel-tech/services

backend:
  port: 8020
  dockerfile_path: home-manager/Dockerfile
  working_directory: home-manager

frontend:
  framework: flutter
  working_directory: modules/asset-managers/home-manager/frontend/app/home_app
  base_path: /

aws:
  ecr_repository: home-manager
  ecs_service: home-manager-service
  ecs_cluster: "${environment}-cluster"
  container_name: home-manager
  region: us-east-1
