app:
  name: meal-planner
  repository: rummel-tech/services

backend:
  port: 8010
  dockerfile_path: meal-planner/Dockerfile
  working_directory: meal-planner

frontend:
  framework: flutter
  working_directory: modules/planners/meal-planner/frontend/app/meals_app
  base_path: /

aws:
  ecr_repository: meal-planner
  ecs_service: meal-planner-service
  ecs_cluster: "${environment}-cluster"
  container_name: meal-planner
  region: us-east-1
