app:
  name: vehicle-manager
  repository: rummel-tech/services

backend:
  port: 8030
  dockerfile_path: vehicle-manager/Dockerfile
  working_directory: vehicle-manager

frontend:
  framework: flutter
  working_directory: modules/asset-managers/vehicle-manager/frontend/app/vehicle_app
  base_path: /

aws:
  ecr_repository: vehicle-manager
  ecs_service: vehicle-manager-service
  ecs_cluster: "${environment}-cluster"
  container_name: vehicle-manager
  region: us-east-1
