app:
  name: workout-planner
  repository: rummel-tech/services

backend:
  port: 8000
  dockerfile_path: workout-planner/Dockerfile
  working_directory: workout-planner

frontend:
  framework: flutter
  working_directory: modules/planners/workout-planner
  base_path: /

aws:
  ecr_repository: workout-planner
  ecs_service: workout-planner-service
  ecs_cluster: "${environment}-cluster"
  container_name: workout-planner
  region: us-east-1
